import type { Metadata } from "next";
import {JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import {Navbar} from "@/components/Navbar";

const jetbrainsMono = JetBrains_Mono({subsets:['latin'],variable:'--font-mono'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased",jetbrainsMono.variable)}
    >
      <body className="min-h-full flex flex-col">
      <Navbar/>
      <main className="grow container mx-auto px-4 py-8">
        {children}
      </main>
      </body>
    </html>
  );
}
